services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: parking
      POSTGRES_DB: parking
    volumes:
      - db_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: parking
      POSTGRES_DB: parking_test

volumes:
  db_data:
